spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sumanth?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Nithiin@reddy25


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true

  #JPA Settings
  jpa.hibernate.ddl_auto: create

  logging:
    config: classpath:log4j2.xml
tomorrowDocsApi:
  baseUrl: https://api.tomorrow.io/v4/weather/forecast?location=
  appId: 5PMczKAScEfw5HuNX8boYvRbuAgFdO3H

