spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sumanth?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Nithiin@reddy25


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true

  #JPA Settings
  jpa.hibernate.ddl_auto: update
  
  logging:
    config: classpath:log4j2.xml
openWeatherApp:
  baseUrl: https://api.openweathermap.org/data/2.5
  defaultLocation: ",us"
  appId: 7fa18767eaab164c34d8b800a6a12872

